project:
  type: manuscript
  # type: website

manuscript:
  article: index.qmd
  code-links: [repo]
  notebooks:
    - notebook: notebooks/stats.qmd

website:
  sidebar:
    contents: auto
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Presentation"
        menu:
          - href: presentations/grp.qmd
            text: Group Meeting
          - href: presentations/sparthb.qmd
            text: SPARTHB

format:
  html:
    toc: true
    code-fold: true
    lightbox: auto

bibliography:
  - files/bibliography/research.bib

wrap: preserve

execute:
  eval: false

engines: [julia]

citation:
  container-title: "JGR: Space Physics"
